# Generated by Django 6.0 on 2026-01-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_checkin_minutes_spent_checkin_xp_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='achievements_unlocked',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
