# Generated by Django 6.0rc1 on 2026-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_playerprofile_daily_quest_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='used_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='freeze_milestones_claimed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='recovery_quest_claimed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='recovery_quest_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='streak_freeze_charges',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
